version: "3.3"
services:
  foo:
    environment:
      - NGINX_PORT:8080
    build:
      context: ./foo-container
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  bar:
    environment:
      - NGINX_PORT:9090
    build:
      context: ./bar-container
      dockerfile: Dockerfile
    ports:
      - 9090:9090